// <auto-generated />
namespace MunicipalTrashProgram.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedstartendandvacationtouserinfo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedstartendandvacationtouserinfo));
        
        string IMigrationMetadata.Id
        {
            get { return "201609191332400_added start end and vacation to userinfo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
